# Generated by Django 3.2.13 on 2022-04-20 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sf_hw_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeIgnore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore', models.ManyToManyField(related_name='ignore', to=settings.AUTH_USER_MODEL, verbose_name='ignore')),
                ('subscriber', models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='subscribers')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(default='caption', max_length=250, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_name'),
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
